language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libsparsehash-dev
script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
